import { 
  Profile, 
  Conversation, 
  Message, 
  Friend, 
  FriendRequest, 
  GroupItem, 
  ChannelItem, 
  SparkItem, 
  ActivityNotification,
  PrivacySettings,
  ChatPreferences
} from '../types';

export const MAYA_USER: Profile = {
  id: 'user-maya-001',
  name: 'Maya Lin',
  display_name: 'Maya Lin',
  username: 'mayalin',
  email: 'maya@bunnytalks.com',
  avatar_url: '/assets/maya.png',
  bio: 'Product Designer @ Bunny. Coffee lover, pixel perfectionist, and rabbit enthusiast 🐰✨',
  mood_status: '✨ Designing cool things',
  status_message: 'Available on Bunny Talks',
  is_online: true,
  presence_status: 'online',
  friends_count: 48,
  sparks_count: 1420,
  groups_count: 12,
  channels_count: 15,
  created_at: new Date(Date.now() - 86400000 * 90).toISOString(),
};

export const LIAM_USER: Profile = {
  id: 'user-liam-002',
  name: 'Liam Chen',
  display_name: 'Liam Chen',
  username: 'liamchen',
  email: 'liam@bunnytalks.com',
  avatar_url: '/assets/alex.png',
  bio: 'Graphic & Sound Designer. Curating cozy beats & smooth interfaces 🎧',
  mood_status: '🎧 Late Night Lo-fi',
  status_message: 'Active now • Product Squad',
  is_online: true,
  presence_status: 'online',
  friends_count: 64,
  sparks_count: 310,
  groups_count: 8,
  channels_count: 9,
  last_seen_at: new Date().toISOString(),
  created_at: new Date(Date.now() - 86400000 * 120).toISOString(),
};

export const SOPHIE_USER: Profile = {
  id: 'user-sophie-003',
  name: 'Sophie Park',
  display_name: 'Sophie Park',
  username: 'sophie_p',
  email: 'sophie@bunnytalks.com',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
  bio: 'Architectural photographer & matcha addict 🍵',
  mood_status: '☕ In café',
  status_message: 'Active 8m ago',
  is_online: true,
  presence_status: 'away',
  friends_count: 89,
  sparks_count: 540,
  groups_count: 14,
  channels_count: 22,
  last_seen_at: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  created_at: new Date(Date.now() - 86400000 * 80).toISOString(),
};

export const NOAH_USER: Profile = {
  id: 'user-noah-004',
  name: 'Noah Vance',
  display_name: 'Noah Vance',
  username: 'noah_vance',
  email: 'noah@bunnytalks.com',
  avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
  bio: 'Web3 & Indie Game Dev 🕹️ Building Bunny arcade games.',
  mood_status: '🎮 Gaming',
  status_message: 'Online on desktop',
  is_online: true,
  presence_status: 'online',
  friends_count: 112,
  sparks_count: 198,
  groups_count: 6,
  channels_count: 11,
  last_seen_at: new Date().toISOString(),
  created_at: new Date(Date.now() - 86400000 * 60).toISOString(),
};

export const CHLOE_USER: Profile = {
  id: 'user-chloe-005',
  name: 'Chloe Rivera',
  display_name: 'Chloe Rivera',
  username: 'chloe_r',
  email: 'chloe@bunnytalks.com',
  avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
  bio: 'Creative Producer & Botanical Illustrator 🌿',
  mood_status: '🌿 Botanical mood',
  status_message: 'Active 2h ago',
  is_online: false,
  presence_status: 'invisible',
  friends_count: 73,
  sparks_count: 420,
  groups_count: 9,
  channels_count: 18,
  last_seen_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  created_at: new Date(Date.now() - 86400000 * 45).toISOString(),
};

export const ALL_PROFILES: Profile[] = [MAYA_USER, LIAM_USER, SOPHIE_USER, NOAH_USER, CHLOE_USER];

export const INITIAL_FRIENDS: Friend[] = [
  {
    id: 'f-1',
    user_id: MAYA_USER.id,
    friend_profile: LIAM_USER,
    mutual_friends_count: 18,
    status: 'online',
    activity: 'Active now • Product Squad',
  },
  {
    id: 'f-2',
    user_id: MAYA_USER.id,
    friend_profile: SOPHIE_USER,
    mutual_friends_count: 12,
    status: 'online',
    activity: 'Active 8m ago • In café',
  },
  {
    id: 'f-3',
    user_id: MAYA_USER.id,
    friend_profile: NOAH_USER,
    mutual_friends_count: 9,
    status: 'online',
    activity: 'Streaming indie games',
  },
  {
    id: 'f-4',
    user_id: MAYA_USER.id,
    friend_profile: CHLOE_USER,
    mutual_friends_count: 14,
    status: 'offline',
    activity: 'Active 2h ago',
  },
];

export const INITIAL_FRIEND_REQUESTS: FriendRequest[] = [
  {
    id: 'fr-1',
    sender_id: 'user-alex-006',
    receiver_id: MAYA_USER.id,
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    sender: {
      id: 'user-alex-006',
      name: 'Alex Rivera',
      username: 'alex_r',
      avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
      bio: 'Motion designer & 3D character artist 🎨',
      mood_status: '🚀 Rendering scenes',
      is_online: true,
      presence_status: 'online',
      friends_count: 42,
    },
    mutual_count: 7,
  },
  {
    id: 'fr-2',
    sender_id: 'user-mia-007',
    receiver_id: MAYA_USER.id,
    status: 'pending',
    created_at: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    sender: {
      id: 'user-mia-007',
      name: 'Mia Taylor',
      username: 'miataylor',
      avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
      bio: 'Community Manager & Bunny Talks enthusiast ✨',
      mood_status: '✨ Hosting hangouts',
      is_online: false,
      presence_status: 'away',
      friends_count: 156,
    },
    mutual_count: 12,
  },
];

export const INITIAL_GROUPS: GroupItem[] = [
  {
    id: 'grp-1',
    name: 'Product Squad',
    description: 'Daily syncs, design critiques, and roadmap discussions for Bunny Talks.',
    avatar_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&auto=format&fit=crop&q=80',
    category: 'Product & Tech',
    members_count: 12,
    online_count: 4,
    is_joined: true,
    is_live: true,
    tag: 'LIVE',
    conversation_id: 'conv-group-squad',
  },
  {
    id: 'grp-2',
    name: 'Designers & Bunnies',
    description: 'Sharing Figma kits, micro-interaction prototypes, and warm color palettes.',
    avatar_url: 'https://images.unsplash.com/photo-1558655146-d09347e92766?w=200&auto=format&fit=crop&q=80',
    category: 'Design & UI/UX',
    members_count: 48,
    online_count: 7,
    is_joined: true,
    tag: 'OPEN',
    conversation_id: 'conv-group-design',
  },
  {
    id: 'grp-3',
    name: 'Weekend Kickback',
    description: 'Chill casual hangs, music recommendations, and gaming sessions.',
    avatar_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=200&auto=format&fit=crop&q=80',
    category: 'Social & Leisure',
    members_count: 103,
    online_count: 15,
    is_joined: true,
    tag: 'JOINED',
  },
  {
    id: 'grp-4',
    name: 'Frontend Wizards',
    description: 'React 19, TypeScript, WebRTC, and Tailwind glass design patterns.',
    avatar_url: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=200&auto=format&fit=crop&q=80',
    category: 'Engineering',
    members_count: 82,
    online_count: 19,
    is_joined: false,
    tag: 'DISCOVER',
  },
];

export const INITIAL_CHANNELS: ChannelItem[] = [
  {
    id: 'chan-1',
    name: 'Design Systems & Co',
    description: 'Curated design tokens, mobile typography, and soft glass elevation tips.',
    icon_emoji: '🎨',
    subscribers_count: 18240,
    category: 'Design',
    is_subscribed: true,
    new_badge: '12',
    latest_post: {
      title: 'Glassmorphism Tokens in 2026',
      preview: 'Check out our new guide on soft shadows and backdrop filters for mobile viewports.',
      time: '5 min ago',
      likes: 248,
    },
  },
  {
    id: 'chan-2',
    name: 'Lo-Fi Corner',
    description: 'Chill instrumental beats for coding, designing, and relaxing sessions.',
    icon_emoji: '🎵',
    subscribers_count: 42100,
    category: 'Music',
    is_subscribed: true,
    new_badge: '4',
    latest_post: {
      title: 'New Spring Mix • Rainy Rooftop',
      preview: '45 minutes of warm analog tape loops and mellow electric piano.',
      time: '18 min ago',
      likes: 512,
    },
  },
  {
    id: 'chan-3',
    name: 'Bunny Developers',
    description: 'Official releases, API changelog, and SDK updates for Bunny Talks.',
    icon_emoji: '💻',
    subscribers_count: 7850,
    category: 'Developers',
    is_subscribed: true,
    new_badge: 'NEW',
    latest_post: {
      title: 'Bunny Realtime Sync 2.0 Released',
      preview: 'Lower latency WebRTC channels, presence pings, and rich reactions are here!',
      time: '1 hour ago',
      likes: 384,
    },
  },
  {
    id: 'chan-4',
    name: 'Friday Night Design',
    description: 'Weekly creative prompts, showcase your personal projects and sparks.',
    icon_emoji: '🪩',
    subscribers_count: 9400,
    category: 'Community',
    is_subscribed: false,
    latest_post: {
      title: '“What are you building this weekend?”',
      preview: 'Drop your screenshots, prototypes, or sketches in the comments below!',
      time: '2 hours ago',
      likes: 195,
    },
  },
];

export const INITIAL_SPARKS: SparkItem[] = [
  {
    id: 'spark-1',
    user_id: LIAM_USER.id,
    user_name: 'Liam Chen',
    user_avatar: '/assets/alex.png',
    user_handle: '@liamchen',
    type: 'music',
    title: 'Late Night Lo-fi Beats',
    caption: 'Tuning synth patches for the new ambient playlist. What are you listening to tonight? 🎧',
    media_url: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=600&auto=format&fit=crop&q=80',
    track_title: 'Late Night Lo-fi',
    track_artist: 'Bunny Chill Session',
    mood_badge: '🎧 Beats',
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    expires_in: '23h',
    reactions_count: 42,
    comments_count: 8,
    views_count: 184,
    reactors: ['Maya Lin', 'Sophie Park', 'Noah Vance'],
  },
  {
    id: 'spark-2',
    user_id: SOPHIE_USER.id,
    user_name: 'Sophie Park',
    user_avatar: SOPHIE_USER.avatar_url,
    user_handle: '@sophie_p',
    type: 'photo',
    title: 'Coffee + conversations ☕',
    caption: 'Soft sunlight, warm cortado, and reviewing wireframes at the greenhouse cafe 🌿✨',
    media_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&auto=format&fit=crop&q=80',
    mood_badge: '☕ In café',
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    expires_in: '21h',
    reactions_count: 56,
    comments_count: 14,
    views_count: 230,
    reactors: ['Maya Lin', 'Liam Chen'],
  },
  {
    id: 'spark-3',
    user_id: NOAH_USER.id,
    user_name: 'Noah Vance',
    user_avatar: NOAH_USER.avatar_url,
    user_handle: '@noah_vance',
    type: 'photo',
    title: 'Weekend sketchbook ✏️',
    caption: 'Sketching bunny mascot stickers for the community drop! Vote for your favorite sticker 🐰',
    media_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    mood_badge: '🎮 Gaming',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    expires_in: '19h',
    reactions_count: 38,
    comments_count: 6,
    views_count: 165,
    reactors: ['Liam Chen', 'Maya Lin'],
  },
  {
    id: 'spark-4',
    user_id: MAYA_USER.id,
    user_name: 'Maya Lin',
    user_avatar: '/assets/maya.png',
    user_handle: '@mayalin',
    type: 'text',
    title: 'Soft Sunday ☕',
    caption: 'Exploring tactile glassmorphic surfaces and micro-interactions. The future of friendly chat is soft! ✨🐰',
    bg_gradient: 'linear-gradient(135deg, #ff607d 0%, #7b5cf5 100%)',
    mood_badge: '✨ Designing',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    expires_in: '18h',
    reactions_count: 84,
    comments_count: 22,
    views_count: 320,
    reactors: ['Liam Chen', 'Sophie Park', 'Noah Vance', 'Chloe Rivera'],
  },
];

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-liam-direct',
    type: 'direct',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
    last_message_at: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    is_pinned: true,
    members: [
      { id: 'm-maya', conversation_id: 'conv-liam-direct', user_id: MAYA_USER.id, joined_at: new Date().toISOString(), profile: MAYA_USER },
      { id: 'm-liam', conversation_id: 'conv-liam-direct', user_id: LIAM_USER.id, joined_at: new Date().toISOString(), profile: LIAM_USER },
    ],
    other_user: LIAM_USER,
    unread_count: 2,
    last_message: {
      id: 'msg-liam-last',
      conversation_id: 'conv-liam-direct',
      sender_id: LIAM_USER.id,
      message_type: 'text',
      content: 'Can you review the new Bunny prototype? Check out the radiant accents!',
      created_at: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
      status: 'delivered',
    },
  },
  {
    id: 'conv-group-squad',
    type: 'group',
    title: 'Product Squad',
    avatar_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=200&auto=format&fit=crop&q=80',
    description: 'Product design, roadmap reviews, and sprint planning.',
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
    updated_at: new Date().toISOString(),
    last_message_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
    is_pinned: true,
    members: [
      { id: 'm-g-1', conversation_id: 'conv-group-squad', user_id: MAYA_USER.id, joined_at: new Date().toISOString(), role: 'admin', profile: MAYA_USER },
      { id: 'm-g-2', conversation_id: 'conv-group-squad', user_id: LIAM_USER.id, joined_at: new Date().toISOString(), role: 'member', profile: LIAM_USER },
      { id: 'm-g-3', conversation_id: 'conv-group-squad', user_id: SOPHIE_USER.id, joined_at: new Date().toISOString(), role: 'member', profile: SOPHIE_USER },
    ],
    unread_count: 0,
    last_message: {
      id: 'msg-sq-last',
      conversation_id: 'conv-group-squad',
      sender_id: SOPHIE_USER.id,
      message_type: 'text',
      content: 'Sophie: Let’s review at 3pm sharp!',
      created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
      status: 'read',
    },
  },
  {
    id: 'conv-noah-direct',
    type: 'direct',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    updated_at: new Date().toISOString(),
    last_message_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    is_pinned: false,
    members: [
      { id: 'm-n-1', conversation_id: 'conv-noah-direct', user_id: MAYA_USER.id, joined_at: new Date().toISOString(), profile: MAYA_USER },
      { id: 'm-n-2', conversation_id: 'conv-noah-direct', user_id: NOAH_USER.id, joined_at: new Date().toISOString(), profile: NOAH_USER },
    ],
    other_user: NOAH_USER,
    unread_count: 0,
    last_message: {
      id: 'msg-noah-last',
      conversation_id: 'conv-noah-direct',
      sender_id: NOAH_USER.id,
      message_type: 'text',
      content: 'Haha that bunny sticker is hilarious 😂',
      created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      status: 'read',
    },
  },
  {
    id: 'conv-chloe-direct',
    type: 'direct',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
    updated_at: new Date().toISOString(),
    last_message_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    is_pinned: false,
    members: [
      { id: 'm-c-1', conversation_id: 'conv-chloe-direct', user_id: MAYA_USER.id, joined_at: new Date().toISOString(), profile: MAYA_USER },
      { id: 'm-c-2', conversation_id: 'conv-chloe-direct', user_id: CHLOE_USER.id, joined_at: new Date().toISOString(), profile: CHLOE_USER },
    ],
    other_user: CHLOE_USER,
    unread_count: 0,
    last_message: {
      id: 'msg-chloe-last',
      conversation_id: 'conv-chloe-direct',
      sender_id: CHLOE_USER.id,
      message_type: 'image',
      content: 'Shared 3 photos from brunch 🥐',
      created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
      status: 'read',
    },
  },
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  'conv-liam-direct': [
    {
      id: 'msg-1',
      conversation_id: 'conv-liam-direct',
      sender_id: LIAM_USER.id,
      message_type: 'text',
      content: 'Hey Maya! Did you get a chance to review the new Bunny prototype? 🐰',
      created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
      status: 'read',
      sender: LIAM_USER,
      reactions: [{ id: 'r1', message_id: 'msg-1', user_id: MAYA_USER.id, reaction: '❤️', created_at: new Date().toISOString() }],
    },
    {
      id: 'msg-2',
      conversation_id: 'conv-liam-direct',
      sender_id: MAYA_USER.id,
      message_type: 'text',
      content: 'Yes! Loving the warm radiant color palette, soft glass cards, and the micro-interactions.',
      created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      status: 'read',
      sender: MAYA_USER,
    },
    {
      id: 'msg-3',
      conversation_id: 'conv-liam-direct',
      sender_id: LIAM_USER.id,
      message_type: 'voice',
      content: 'Voice note (0:14)',
      media_url: 'https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg',
      metadata: { duration: 14, waveform: [3, 8, 14, 20, 16, 9, 22, 18, 12, 16, 8, 4] },
      created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
      status: 'read',
      sender: LIAM_USER,
      reactions: [{ id: 'r2', message_id: 'msg-3', user_id: MAYA_USER.id, reaction: '🔥', created_at: new Date().toISOString() }],
    },
    {
      id: 'msg-4',
      conversation_id: 'conv-liam-direct',
      sender_id: LIAM_USER.id,
      message_type: 'text',
      content: 'Perfect. I also added the new Spark flow. Want to test it together?',
      created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      status: 'read',
      sender: LIAM_USER,
    },
    {
      id: 'msg-5',
      conversation_id: 'conv-liam-direct',
      sender_id: MAYA_USER.id,
      message_type: 'text',
      content: 'Absolutely 🐰 Send it over! I am ready to test the live updates.',
      created_at: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
      status: 'read',
      sender: MAYA_USER,
    },
    {
      id: 'msg-6',
      conversation_id: 'conv-liam-direct',
      sender_id: LIAM_USER.id,
      message_type: 'text',
      content: 'Can you review the new Bunny prototype? Check out the radiant accents!',
      created_at: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
      status: 'delivered',
      sender: LIAM_USER,
    },
  ],
  'conv-group-squad': [
    {
      id: 'gmsg-1',
      conversation_id: 'conv-group-squad',
      sender_id: LIAM_USER.id,
      message_type: 'text',
      content: 'Morning team! Standup in 15 minutes. 🐰',
      created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
      status: 'read',
      sender: LIAM_USER,
    },
    {
      id: 'gmsg-2',
      conversation_id: 'conv-group-squad',
      sender_id: MAYA_USER.id,
      message_type: 'text',
      content: 'Finished the responsive application shell and dark mode theme switching!',
      created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
      status: 'read',
      sender: MAYA_USER,
    },
    {
      id: 'gmsg-3',
      conversation_id: 'conv-group-squad',
      sender_id: SOPHIE_USER.id,
      message_type: 'text',
      content: 'Sophie: Let’s review at 3pm sharp!',
      created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
      status: 'read',
      sender: SOPHIE_USER,
      reactions: [{ id: 'rg1', message_id: 'gmsg-3', user_id: MAYA_USER.id, reaction: '👍', created_at: new Date().toISOString() }],
    },
  ],
};

export const INITIAL_NOTIFICATIONS: ActivityNotification[] = [
  {
    id: 'act-1',
    type: 'friend_request',
    title: 'Alex Rivera',
    description: 'sent you a friend request (7 mutual friends)',
    time: '35m ago',
    is_read: false,
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    action_label: 'Accept',
    action_type: 'accept_request',
  },
  {
    id: 'act-2',
    type: 'reaction',
    title: 'Liam Chen',
    description: 'reacted ❤️ to your message in “Liam Chen”',
    time: '42m ago',
    is_read: false,
    avatar_url: '/assets/alex.png',
    icon_emoji: '❤️',
  },
  {
    id: 'act-3',
    type: 'spark_activity',
    title: 'Sophie Park',
    description: 'viewed your Spark “Designing the new Bunny Glass UI”',
    time: '1h ago',
    is_read: true,
    avatar_url: SOPHIE_USER.avatar_url,
    icon_emoji: '⚡',
  },
  {
    id: 'act-4',
    type: 'channel_update',
    title: 'Design Systems & Co',
    description: 'posted “Glassmorphism Tokens in 2026”',
    time: '2h ago',
    is_read: true,
    icon_emoji: '🎨',
  },
  {
    id: 'act-5',
    type: 'group_invite',
    title: 'Designers & Bunnies',
    description: 'Sophie invited you to live voice room',
    time: '3h ago',
    is_read: true,
    avatar_url: SOPHIE_USER.avatar_url,
    icon_emoji: '🎧',
  },
];

export const DEFAULT_PRIVACY: PrivacySettings = {
  last_seen_visibility: 'everyone',
  profile_photo_visibility: 'everyone',
  online_status_visibility: 'everyone',
  read_receipts: true,
  who_can_message_me: 'everyone',
  who_can_add_to_groups: 'everyone',
};

export const DEFAULT_CHAT_PREFERENCES: ChatPreferences = {
  enter_to_send: true,
  media_auto_download: true,
  sound_effects: true,
  message_preview: true,
  theme_accent: 'coral',
};

export const mockUsers = ALL_PROFILES;
